services:
  db:
    image: mysql:8.0   
    restart: always
    env_file:
      - stack.env
    volumes:
      - wordpress-db:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    env_file:
      - stack.env
    volumes:
      - wordpress-data:/var/www/html  

volumes:
  wordpress-db:
  wordpress-data:
